:general:
  date_template: "%Y-%m-%d"

:templates:
  - { location: /data/pac-templates/minimal.md, output: minimal-report.md }
  - { location: /data/pac-templates/html-minimal.html, output: html-minimal.html , pdf: true}

:task_systems:
  -
    :name: none
    :regex:
      - { pattern: '/(PAC-\d+)/', label: none }
      - { pattern: '/(TODO-\d+)/', label: todo }

:vcs:
  :type: git
  :repo_location: '.'